// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czrosatosvrjkzxkaqxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6cm9zYXRvc3Zyamt6eGthcXhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NjUxNTAsImV4cCI6MjA3MTI0MTE1MH0.8KsbnraVJZ4oDwtqkZ5n11SO2kMR8ZjSJBIkMmALrtc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});